2020-11-17 09:25:30,565 INFO    MainThread:40940 [wandb_setup.py:_flush():68] setting env: {}
2020-11-17 09:25:30,566 INFO    MainThread:40940 [wandb_setup.py:_flush():68] multiprocessing start_methods=fork,spawn,forkserver
2020-11-17 09:25:30,566 INFO    MainThread:40940 [wandb_setup.py:_flush():68] setting login settings: {}
2020-11-17 09:25:30,566 INFO    MainThread:40940 [wandb_init.py:_log_setup():302] Logging user logs to /Users/zhouhan/Downloads/2020大三资料/2020秋自动化测试/MobileAutomatedTesting/yolov5/wandb/run-20201117_092530-2ycoxido/logs/debug.log
2020-11-17 09:25:30,566 INFO    MainThread:40940 [wandb_init.py:_log_setup():303] Logging internal logs to /Users/zhouhan/Downloads/2020大三资料/2020秋自动化测试/MobileAutomatedTesting/yolov5/wandb/run-20201117_092530-2ycoxido/logs/debug-internal.log
2020-11-17 09:25:33,286 INFO    MainThread:40940 [wandb_run.py:_console_start():1213] atexit reg
2020-11-17 09:25:33,287 INFO    MainThread:40940 [wandb_run.py:_redirect():1083] redirect: SettingsConsole.REDIRECT
2020-11-17 09:25:33,287 INFO    MainThread:40940 [wandb_run.py:_redirect():1086] Redirecting console.
2020-11-17 09:25:33,287 INFO    MainThread:40940 [redirect.py:install():204] install start
2020-11-17 09:25:33,288 INFO    MainThread:40940 [redirect.py:install():219] install stop
2020-11-17 09:25:33,288 INFO    MainThread:40940 [redirect.py:install():204] install start
2020-11-17 09:25:33,288 INFO    MainThread:40940 [redirect.py:install():219] install stop
2020-11-17 09:25:33,288 INFO    MainThread:40940 [wandb_run.py:_redirect():1130] Redirects installed.
2020-11-17 09:25:33,374 INFO    MainThread:40940 [wandb_run.py:_atexit_cleanup():1186] got exitcode: 1
2020-11-17 09:25:33,374 INFO    MainThread:40940 [wandb_run.py:_restore():1158] restore
2020-11-17 09:25:33,374 INFO    MainThread:40940 [redirect.py:uninstall():223] uninstall start
2020-11-17 09:25:33,375 INFO    MainThread:40940 [redirect.py:_stop():278] _stop: stdout
2020-11-17 09:25:33,375 INFO    MainThread:40940 [redirect.py:_stop():284] _stop closed: stdout
2020-11-17 09:25:33,375 INFO    stdout    :40940 [redirect.py:_pipe_relay():120] relay done saw last write: stdout
2020-11-17 09:25:33,375 INFO    stdout    :40940 [redirect.py:_pipe_relay():136] relay done done: stdout
2020-11-17 09:25:33,375 INFO    MainThread:40940 [redirect.py:_stop():290] _stop joined: stdout
2020-11-17 09:25:33,375 INFO    MainThread:40940 [redirect.py:_stop():292] _stop rd closed: stdout
2020-11-17 09:25:33,375 INFO    MainThread:40940 [redirect.py:uninstall():227] uninstall done
2020-11-17 09:25:33,375 INFO    MainThread:40940 [redirect.py:uninstall():223] uninstall start
2020-11-17 09:25:33,375 INFO    MainThread:40940 [redirect.py:_stop():278] _stop: stderr
2020-11-17 09:25:33,375 INFO    MainThread:40940 [redirect.py:_stop():284] _stop closed: stderr
2020-11-17 09:25:33,376 INFO    stderr    :40940 [redirect.py:_pipe_relay():120] relay done saw last write: stderr
2020-11-17 09:25:33,376 INFO    stderr    :40940 [redirect.py:_pipe_relay():136] relay done done: stderr
2020-11-17 09:25:33,376 INFO    MainThread:40940 [redirect.py:_stop():290] _stop joined: stderr
2020-11-17 09:25:33,376 INFO    MainThread:40940 [redirect.py:_stop():292] _stop rd closed: stderr
2020-11-17 09:25:33,376 INFO    MainThread:40940 [redirect.py:uninstall():227] uninstall done
2020-11-17 09:25:33,676 INFO    MainThread:40940 [wandb_run.py:_wait_for_finish():1300] got exit ret: uuid: "c34bc40f5c444faabda129a1bac96385"
response {
  poll_exit_response {
    file_counts {
      wandb_count: 1
    }
    pusher_stats {
      total_bytes: 959
    }
  }
}

2020-11-17 09:25:35,682 INFO    MainThread:40940 [wandb_run.py:_wait_for_finish():1300] got exit ret: uuid: "fb7cf9491b784271a3bb30912d4969f8"
response {
  poll_exit_response {
    done: true
    exit_result {
    }
    file_counts {
      wandb_count: 5
    }
    pusher_stats {
      uploaded_bytes: 5621
      total_bytes: 5621
    }
  }
}

2020-11-17 09:25:36,760 INFO    MainThread:40940 [wandb_run.py:_show_files():1509] logging synced files
2020-11-17 09:25:36,763 INFO    MainThread:40940 [internal.py:handle_exit():138] Internal process exited
