WARNING: --img-size 2440 must be multiple of max stride 32, updating to 2464
WARNING: --img-size 2440 must be multiple of max stride 32, updating to 2464
Scanning images:   0%|          | 0/1004 [00:00<?, ?it/s]Scanning images:  16%|█▌        | 156/1004 [00:00<00:00, 1554.39it/s]Scanning images:  37%|███▋      | 368/1004 [00:00<00:00, 1688.10it/s]Scanning images:  57%|█████▋    | 576/1004 [00:00<00:00, 1789.19it/s]Scanning images:  79%|███████▉  | 793/1004 [00:00<00:00, 1887.89it/s]Scanning images: 100%|██████████| 1004/1004 [00:00<00:00, 2020.30it/s]
0it [00:00, ?it/s]Scanning labels ../pics/labels/train2020.cache (1 found, 0 missing, 0 empty, 0 duplicate, for 1004 images): 1it [00:00, 2416.07it/s]
Traceback (most recent call last):
  File "train.py", line 482, in <module>
    train(hyp, opt, device, tb_writer, wandb)
  File "train.py", line 175, in train
    dataloader, dataset = create_dataloader(train_path, imgsz, batch_size, gs, opt,
  File "/Users/zhouhan/Downloads/2020大三资料/2020秋自动化测试/MobileAutomatedTesting/yolov5/utils/datasets.py", line 59, in create_dataloader
    dataset = LoadImagesAndLabels(path, imgsz, batch_size,
  File "/Users/zhouhan/Downloads/2020大三资料/2020秋自动化测试/MobileAutomatedTesting/yolov5/utils/datasets.py", line 420, in __init__
    assert (l[:, 1:] <= 1).all(), 'non-normalized or out of bounds coordinate labels: %s' % file
AssertionError: non-normalized or out of bounds coordinate labels: ../pics/labels/train2020/10418.txt
